export type Device = {
    id: string;
    room: "drawing" | "workroom_1" | "workroom_2";
    type: "fan" | "light";
    name: string;
    powerRating: number;
    wattage: number;
    isOn: boolean;
    lastChanged: number;
}

export const devices : Device[] = [
  {
    id: "drawing-fan-1",
    room: "drawing",
    type: "fan",
    name: "Fan 1",
    powerRating: 60,
    wattage: 60,
    isOn: true,
    lastChanged: Date.now(),
  },
  {
    id: "drawing-fan-2",
    room: "drawing",
    type: "fan",
    name: "Fan 2",
    powerRating: 60,
    wattage: 60,
    isOn: true,
    lastChanged: Date.now(),
  },
  {
    id: "drawing-light-1",
    room: "drawing",
    type: "light",
    name: "Light 1",
    powerRating: 15,
    wattage: 15,
    isOn: true,
    lastChanged: Date.now(),
  },
  {
    id: "drawing-light-2",
    room: "drawing",
    type: "light",
    name: "Light 2",
    powerRating: 15,
    wattage: 15,
    isOn: true,
    lastChanged: Date.now(),
  },
  {
    id: "drawing-light-3",
    room: "drawing",
    type: "light",
    name: "Light 3",
    powerRating: 15,
    wattage: 15,
    isOn: true,
    lastChanged: Date.now(),
  },
  {
    id: "workroom-1-fan-1",
    room: "workroom_1",
    type: "fan",
    name: "Fan 1",
    wattage: 60,
    powerRating: 60,
    isOn: true,
    lastChanged: Date.now(),
  },
  {
    id: "workroom-1-fan-2",
    room: "workroom_1",
    type: "fan",
    name: "Fan 2",
    wattage: 60,
    powerRating: 60,
    isOn: true,
    lastChanged: Date.now(),
  },
  {
    id: "workroom-1-light-1",
    room: "workroom_1",
    type: "light",
    name: "Light 1",
    wattage: 15,
    powerRating: 15,
    isOn: true,
    lastChanged: Date.now(),
  },
  {
    id: "workroom-1-light-2",
    room: "workroom_1",
    type: "light",
    name: "Light 2",
    powerRating: 15,
    wattage: 15,
    isOn: true,
    lastChanged: Date.now(),
  },
  {
    id: "workroom-1-light-3",
    room: "workroom_1",
    type: "light",
    name: "Light 3",
    wattage: 15,
    powerRating: 15,
    isOn: true,
    lastChanged: Date.now(),
  },
  {
    id: "workroom-2-fan-1",
    room: "workroom_2",
    type: "fan",
    name: "Fan 1",
    wattage: 60,
    powerRating: 60,
    isOn: true,
    lastChanged: Date.now(),
  },
  {
    id: "workroom-2-fan-2",
    room: "workroom_2",
    type: "fan",
    name: "Fan 2",
    wattage: 60,
    powerRating: 60,
    isOn: true,
    lastChanged: Date.now(),
  },
  {
    id: "workroom-2-light-1",
    room: "workroom_2",
    type: "light",
    name: "Light 1",
    wattage: 15,
    powerRating: 15,
    isOn: true,
    lastChanged: Date.now(),
  },
  {
    id: "workroom-2-light-2",
    room: "workroom_2",
    type: "light",
    name: "Light 2",
    wattage: 15,
    powerRating: 15,
    isOn: true,
    lastChanged: Date.now(),
  },
  {
    id: "workroom-2-light-3",
    room: "workroom_2",
    type: "light",
    name: "Light 3",
    wattage: 15,
    powerRating: 15,
    isOn: true,
    lastChanged: Date.now(),
  },
];
